[package]
name = "chsl"
version = "0.1.1"
edition = "2021"
description = "2D Game Physics Engine supporting Joints/Constraints"
license = "MIT"

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true

[features]
# default = ["serde"]
serde = ["dep:serde"]
